{% set name = "eis_toolkit" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GispoCoding/eis_toolkit/archive/v{{ version }}.tar.gz
  sha256: 91e7ad34e6e1c93bda4fcb5e777f47afe298be9888added2d5464d9c142cacb8

build:
  entry_points:
    - eis = eis_toolkit.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - poetry-core >=1.0.0
    - python >=3.9,<3.11
    - pip
  run:
    - python >=3.9.15,<3.11
    - gdal >=3.0.2
    - rasterio >=1.2.10
    - pandas =2.2.2
    - geopandas >=0.12.2,<1.0.0
    - scikit-learn =1.4.2
    - matplotlib-base =3.8.4
    - statsmodels =0.14.2
    - keras >=2.10.0,<3.0.0
    - tensorflow >=2.10.0
    - beartype =0.18.5
    - seaborn =0.13.2
    - pykrige =1.7.1
    - typer =0.12.3
    - imbalanced-learn =0.12.2
    - mapclassify =2.6.1
    - esda =2.5.1
    - scipy =1.13.0

test:
  imports:
    - eis_toolkit
  commands:
    # pip check issues with momepy and giddy having no versions (0.0.0)
    # - pip check
    - eis --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/GispoCoding/eis_toolkit
  summary: 'Python library for mineral prospectivity mapping'
  license: 'EUPL-1.2'
  license_file: LICENSE
  doc_url: https://gispocoding.github.io/eis_toolkit/
  dev_url: https://github.com/GispoCoding/eis_toolkit

extra:
  recipe-maintainers:
    - nialov
    - nmaarnio
