{% set name = "eis_toolkit" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GispoCoding/eis_toolkit/archive/v{{ version }}.tar.gz
  sha256: be51f6cd199b8408bc0a2c6cda03bbefa716da2ac551e5114da58ab1dfe03506

build:
  entry_points:
    - eis = eis_toolkit.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - poetry-core >=1.0.0
    - python >=3.9,<3.11
    - pip
  run:
    - python =3.9.15  # [win]
    - python >=3.9.15,<3.11  # [not win]
    - libgdal =3.0.2  # [win]
    - gdal >=3.0.2  # [not win]
    - rasterio =1.2.10  # [win]
    - rasterio >=1.2.10  # [not win]
    - pandas =2.2.2
    - geopandas =0.12.2  # [win]
    - geopandas >=0.12.2  # [not win]
    - scikit-learn =1.4.2
    - matplotlib-base =3.8.4
    - statsmodels =0.14.2
    - keras =2.10.0  # [win]
    - keras >=2.10.0  # [not win]
    - tensorflow =2.10.0  # [win]
    - tensorflow >=2.10.0  # [not win]
    - beartype =0.18.5
    - seaborn =0.13.2
    - pykrige =1.7.1
    - typer =0.12.3
    - imbalanced-learn =0.12.2
    - mapclassify =2.6.1
    - esda =2.5.1
    - scipy =1.13.0
    - icu =58.2  # [win]

test:
  imports:
    - eis_toolkit
  commands:
    # pip check issues with momepy and giddy having no versions (0.0.0)
    # - pip check
    - eis --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/GispoCoding/eis_toolkit
  summary: 'Python library for mineral prospectivity mapping'
  license: 'EUPL-1.2'
  license_file: LICENSE
  doc_url: https://gispocoding.github.io/eis_toolkit/
  dev_url: https://github.com/GispoCoding/eis_toolkit

extra:
  recipe-maintainers:
    - nialov
    - nmaarnio
