{% set name = "eis_toolkit" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GispoCoding/eis_toolkit/archive/v{{ version }}.tar.gz
  sha256: fd3e2ce26315bfcc3cd8e285db05351d94ad6ee7e56265abf1f4d809620f1ce6

build:
  entry_points:
    - eis = eis_toolkit.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - poetry-core >=1.0.0
    - python >=3.9,<3.11
    - pip
  run:
    - python >=3.9,<3.11
    - gdal >=3.4.3,<4.0.0
    - rasterio >=1.3.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - geopandas >=0.11.1,<0.12.0
    - scikit-learn >=1.1.2,<2.0.0
    - matplotlib-base >=3.5.3,<4.0.0
    - statsmodels >=0.14.0,<0.15.0
    - keras >=2.9.0,<3.0.0
    - tensorflow >=2.9.1,<3.0.0
    - beartype >=0.13.1,<0.14.0
    - seaborn >=0.13.0,<1.0.0
    - pykrige >=1.7.0,<2.0.0
    - rtree >=1.0.1,<2.0.0
    - typer >=0.9.0,<0.10.0
    - imbalanced-learn >=0.11.0,<0.12.0
    - pysal >=23.7.0,<24.0.0
    - esda >=2.5.1,<3.0.0
    - scipy <=1.11.4

test:
  imports:
    - eis_toolkit
  commands:
    # pip check issues with momepy and giddy having no versions (0.0.0)
    # - pip check
    - eis --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/GispoCoding/eis_toolkit
  summary: 'Python library for mineral prospectivity mapping'
  license: 'EUPL-1.2'
  license_file: LICENSE
  doc_url: https://gispocoding.github.io/eis_toolkit/
  dev_url: https://github.com/GispoCoding/eis_toolkit

extra:
  recipe-maintainers:
    - nialov
    - nmaarnio
